# Generated by Django 5.0.4 on 2026-04-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(choices=[('academico', 'Académico'), ('administrativo', 'Administrativo'), ('docente', 'Docente'), ('infraestructura', 'Infraestructura'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('resolucion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Opcional — puede ser anónimo', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('area', models.CharField(choices=[('academico', 'Académico'), ('administrativo', 'Administrativo'), ('infraestructura', 'Infraestructura'), ('tecnologia', 'Tecnología'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('sugerencia', models.TextField()),
                ('respondida', models.BooleanField(default=False)),
                ('respuesta', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sugerencia',
                'verbose_name_plural': 'Sugerencias',
                'ordering': ['-created_at'],
            },
        ),
    ]
