# Generated by Django 5.0.4 on 2026-04-22 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Identificador único. Ej: hero_titulo', max_length=100, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('cuerpo', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido de página',
                'verbose_name_plural': 'Contenidos de páginas',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#1B3D6E', help_text='Color hex para la UI', max_length=7)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('resumen', models.CharField(max_length=500)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('academico', 'Académico'), ('investigacion', 'Investigación'), ('cultural', 'Cultural y Deportivo'), ('institucional', 'Institucional'), ('logros', 'Logros')], default='institucional', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('publicada', models.BooleanField(default=False)),
                ('destacada', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField()),
                ('descripcion_corta', models.CharField(blank=True, max_length=300)),
                ('duracion_anos', models.PositiveSmallIntegerField(default=5)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('semipresencial', 'Semipresencial'), ('virtual', 'Virtual')], default='presencial', max_length=20)),
                ('titulo_otorgado', models.CharField(blank=True, max_length=200)),
                ('perfil_egresado', models.TextField(blank=True)),
                ('emoji', models.CharField(default='🎓', max_length=10)),
                ('color_acento', models.CharField(default='#1B3D6E', max_length=7)),
                ('activa', models.BooleanField(default=True)),
                ('destacada', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facultad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carreras', to='contenido.facultad')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
